# NumPy 

In [48]:
import numpy as np

In [49]:
my_list = [1,2,3]
my_list

[1, 2, 3]

In [53]:
arr = np.array(my_list)
arr

array([1, 2, 3])

In [63]:
my_matrix = [[11,12],[21,22],[31,32]]
my_matrix

[[11, 12], [21, 22], [31, 32]]

In [64]:
arr_2d = np.array(my_matrix)

In [65]:
arr_2d.shape

(3, 2)

## Built-in Methods for array generation

In [67]:
list(range(10))

[0, 1, 2, 3, 4, 5, 6, 7, 8, 9]

In [72]:
np.arange(0,10)

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [87]:
np.arange(0,12,2, dtype=int)

array([ 0,  2,  4,  6,  8, 10])

### zeros and ones

Generate arrays of zeros or ones

In [84]:
mat = np.zeros((3,4, 2))
mat

array([[[0., 0.],
        [0., 0.],
        [0., 0.],
        [0., 0.]],

       [[0., 0.],
        [0., 0.],
        [0., 0.],
        [0., 0.]],

       [[0., 0.],
        [0., 0.],
        [0., 0.],
        [0., 0.]]])

In [85]:
np.astype(mat, int)

array([[[0, 0],
        [0, 0],
        [0, 0],
        [0, 0]],

       [[0, 0],
        [0, 0],
        [0, 0],
        [0, 0]],

       [[0, 0],
        [0, 0],
        [0, 0],
        [0, 0]]])

In [86]:
np.ones(3)

array([1., 1., 1.])

### linspace

In [88]:
np.linspace(0,10, 7)

array([ 0.        ,  1.66666667,  3.33333333,  5.        ,  6.66666667,
        8.33333333, 10.        ])

## eye

In [90]:
np.eye(10)

array([[1., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 1., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 1., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 1., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 1., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 1., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 1., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 1., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 1., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0., 1.]])

## Random

Uniform dist

In [92]:
np.random.rand

<bound method RandomState.rand of RandomState(MT19937) at 0xFFFF80524540>

In [98]:
x = np.random.rand()
x

0.5773080113164536

### randn

Normal dist

In [100]:
np.random.randn(100)

array([-0.31094258, -1.9603449 , -0.25095935,  0.21296715,  1.27666274,
        0.04511676, -0.09594474, -0.82059384,  0.57189   , -0.52833116,
       -0.09209261,  0.58034341,  0.15924669,  1.11071912, -0.11357903,
       -0.75197687, -0.60424222,  0.09450015, -0.38450432, -0.18186818,
        1.07963202, -0.22218761,  0.0375877 , -0.69211733, -0.53932863,
        0.25592323, -0.16504426, -0.72899874, -0.62696979,  0.48444492,
        0.56010515, -0.31178317, -1.37164753, -1.37290074, -0.69865488,
       -0.93456592, -0.31862793, -0.58402081, -0.98977428,  0.30941146,
       -1.28065833,  1.32396017,  0.36325344,  0.77100523, -1.4079899 ,
       -0.87615531,  0.4235157 ,  1.54884249, -1.61866359,  0.22142021,
        1.20600245, -1.13073498,  1.24958473, -0.7199033 , -0.71511373,
        0.86772977,  0.14637748, -1.12361843,  0.0558233 , -3.0105816 ,
        1.35849291, -0.75053222, -2.35298428,  0.10846451,  2.30978651,
       -0.99142249, -0.9949278 , -0.68422966,  0.24759096,  0.04

In [101]:
np.random.randn(5,5)

array([[-0.38699706,  0.51134934, -2.53531046, -1.18761471,  0.49032847],
       [ 0.07321184,  0.46853971,  0.05514024,  0.46985378,  0.48265338],
       [-1.06401917, -0.92186798,  0.59582921, -0.36520852, -0.16237385],
       [ 1.28046057, -0.62485731, -0.67663947,  0.26784808, -1.44973407],
       [-1.64149749, -0.26341432, -0.28699544,  2.14330329, -0.47927958]])

### randint
from `low` (inclusive) to `high` (exclusive).

In [105]:
np.random.randint(1 , 100, (5, 4, 2))

array([[[34, 48],
        [34, 93],
        [23, 46],
        [54, 45]],

       [[16, 32],
        [64, 73],
        [80, 17],
        [69, 10]],

       [[21, 47],
        [ 7, 35],
        [69, 58],
        [48, 56]],

       [[56, 12],
        [ 6, 29],
        [42, 83],
        [ 8, 21]],

       [[94, 62],
        [22, 53],
        [33,  5],
        [14, 15]]])

In [106]:
np.random.randint(1,100,10)

array([99, 37, 44, 36, 15, 49, 30, 47, 94, 23])

## Array Attributes and Methods

Let's discuss some useful attributes and methods or an array:

In [36]:
arr = np.arange(25)
ranarr = np.random.randint(0,50,10)

In [ ]:
arr

In [ ]:
ranarr

## Reshape

In [110]:
x = np.arange(30)

x.reshape(3, 2,5)

array([[[ 0,  1,  2,  3,  4],
        [ 5,  6,  7,  8,  9]],

       [[10, 11, 12, 13, 14],
        [15, 16, 17, 18, 19]],

       [[20, 21, 22, 23, 24],
        [25, 26, 27, 28, 29]]])

In [112]:
np.reshape(x, (3,2,5))

array([[[ 0,  1,  2,  3,  4],
        [ 5,  6,  7,  8,  9]],

       [[10, 11, 12, 13, 14],
        [15, 16, 17, 18, 19]],

       [[20, 21, 22, 23, 24],
        [25, 26, 27, 28, 29]]])

### max,min,argmax,argmin

These are useful methods for finding max or min values. Or to find their index locations using argmin or argmax

In [113]:
ranarr

array([23, 37, 33, 14,  9, 13, 21,  6,  7, 34])

In [114]:
ranarr.max()

np.int64(37)

In [117]:
ranarr.argmax()

np.int64(1)

In [118]:
ranarr.min()

np.int64(6)

In [ ]:
ranarr.argmin()

In [123]:
ranarr.mean()

np.float64(19.7)

## Shape

In [ ]:
# Vector
arr.shape

### dtype

In [ ]:
arr.dtype