# NumPy Indexing

In [28]:
import numpy as np

In [29]:
arr = np.arange(0,11)

In [30]:
arr

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10])

## Bracket Indexing and Selection

In [31]:
arr[4:]

array([ 4,  5,  6,  7,  8,  9, 10])

In [32]:
arr[-3:]

array([ 8,  9, 10])

In [34]:
arr[0:6:2]

array([0, 2, 4])

## Broadcasting

In [35]:
arr[0:5]

array([0, 1, 2, 3, 4])

In [36]:
arr[0:5] = 100

arr

array([100, 100, 100, 100, 100,   5,   6,   7,   8,   9,  10])

In [51]:
x = np.random.randint(0, 30, (4,8))
y = np.arange(3)

x, y

(array([[10, 11,  6,  1, 26, 21, 26, 18],
        [15, 12, 22, 13, 14,  3, 24, 18],
        [20, 22, 11, 17, 26,  5, 13,  6],
        [ 6, 19, 14,  5, 27, 28,  8,  7]]),
 array([0, 1, 2]))

In [52]:
x[:, ::2]

array([[10,  6, 26, 26],
       [15, 22, 14, 24],
       [20, 11, 26, 13],
       [ 6, 14, 27,  8]])

In [ ]:
arr = np.arange(0,11)

arr

In [ ]:
slice_of_arr = arr[0:6]

slice_of_arr

In [ ]:
slice_of_arr[:]=99

slice_of_arr

In [ ]:
arr

In [ ]:
#To get a copy, need to be explicit
arr_copy = arr.copy()

arr_copy

## Indexing multidim

In [53]:
x = [[[111, 112, 113],
      [121, 122, 123],
      [131, 132, 133]
     ],
     [[211, 212, 213],
      [221, 222, 223],
      [231, 232, 233]
     ]
    ]
arr = np.array(x)

arr, arr.shape

(array([[[111, 112, 113],
         [121, 122, 123],
         [131, 132, 133]],
 
        [[211, 212, 213],
         [221, 222, 223],
         [231, 232, 233]]]),
 (2, 3, 3))

In [ ]:
arr[:,2,:]


In [55]:
mask = arr > 123

mask

array([[[False, False, False],
        [False, False, False],
        [ True,  True,  True]],

       [[ True,  True,  True],
        [ True,  True,  True],
        [ True,  True,  True]]])

In [56]:
arr[arr > 123]

array([131, 132, 133, 211, 212, 213, 221, 222, 223, 231, 232, 233])

In [61]:
np.where(mask, arr, 0)

array([[[  0,   0,   0],
        [  0,   0,   0],
        [131, 132, 133]],

       [[211, 212, 213],
        [221, 222, 223],
        [231, 232, 233]]])