# NumPy Operations

## Arithmetic

In [67]:
import numpy as np
x = np.arange(0,10)
y = np.arange(100, 1001, 100)
x, y

(array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9]),
 array([ 100,  200,  300,  400,  500,  600,  700,  800,  900, 1000]))

In [78]:
arr = np.arange(0,10)

In [ ]:
arr * arr

In [ ]:
arr - arr

In [ ]:
# Warning on division by zero, but not an error!
# Just replaced with nan
arr/arr

In [ ]:
1/arr

In [ ]:
arr**3

## Universal Array Functions

In [73]:
np.sqrt(arr)

array([0.        , 1.        , 1.41421356, 1.73205081, 2.        ,
       2.23606798, 2.44948974, 2.64575131, 2.82842712, 3.        ])

In [74]:
np.exp(arr)

array([1.00000000e+00, 2.71828183e+00, 7.38905610e+00, 2.00855369e+01,
       5.45981500e+01, 1.48413159e+02, 4.03428793e+02, 1.09663316e+03,
       2.98095799e+03, 8.10308393e+03])

In [75]:
np.max(arr)

np.int64(9)

In [76]:
np.sin(arr)

array([ 0.        ,  0.84147098,  0.90929743,  0.14112001, -0.7568025 ,
       -0.95892427, -0.2794155 ,  0.6569866 ,  0.98935825,  0.41211849])

In [77]:
np.log(arr)

/tmp/ipykernel_85154/3120950136.py:1: RuntimeWarning: divide by zero encountered in log
  np.log(arr)


array([      -inf, 0.        , 0.69314718, 1.09861229, 1.38629436,
       1.60943791, 1.79175947, 1.94591015, 2.07944154, 2.19722458])

# Matrix operations

In [79]:
A = np.random.randint(0, 10, (3,4))

B = np.random.randint(0, 10, (4,5))

In [82]:
A, B

(array([[5, 7, 5, 6],
        [1, 1, 1, 9],
        [6, 9, 6, 3]]),
 array([[6, 5, 5, 3, 4],
        [4, 0, 1, 3, 9],
        [2, 3, 6, 0, 3],
        [2, 1, 9, 1, 3]]))

In [83]:
np.matmul(A, B), np.dot(A, B)

(array([[ 80,  46, 116,  42, 116],
        [ 30,  17,  93,  15,  43],
        [ 90,  51, 102,  48, 132]]),
 array([[ 80,  46, 116,  42, 116],
        [ 30,  17,  93,  15,  43],
        [ 90,  51, 102,  48, 132]]))

In [84]:
a = np.array([3,4])

np.linalg.norm(a)

np.float64(5.0)

In [85]:
A = np.random.randint(0, 10, (3,3))
b = np.random.randint(1, 9, 3)

A, b

(array([[4, 1, 5],
        [5, 1, 3],
        [4, 7, 6]]),
 array([3, 6, 2]))

In [86]:
x = np.linalg.solve(A, b)
x

array([ 1.62337662, -0.05194805, -0.68831169])

A * x = b
x = A^{-1} * b



In [88]:
x2 = np.dot(np.linalg.inv(A), b)
x2

array([ 1.62337662, -0.05194805, -0.68831169])

In [89]:
x2 == x

array([ True, False, False])

In [90]:
x2 - x

array([ 0.00000000e+00,  2.56739074e-16, -1.11022302e-16])

In [92]:
np.isclose(x2, x, atol=1e-3)

array([ True,  True,  True])